<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="fr-FR">

<head profile="http://gmpg.org/xfn/11">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

<title>ZAP Québec  </title>

<?php
echo $this->headScript()->prependFile($this->baseUrl().'/js/frontend.js', 'text/javascript');
echo $this->headLink()->appendStylesheet('/css/global.css');
	if ($this->jQuery()->isEnabled()) {
		$this->jQuery()->setLocalPath($this->baseUrl().'/js/jquery/js/jquery-1.3.2.min.js')
		               ->setUiLocalPath($this->baseUrl().'/js/jquery/js/jquery-ui-1.7.2.custom.min.js')
		               ->addStylesheet($this->baseUrl().'/js/jquery/css/ui-lightness/jquery-ui-1.7.2.custom.css');
		echo $this->jQuery();
	}
	
	?>
<link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/2.6.0/build/fonts/fonts-min.css" />
<link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/2.6.0/build/reset/reset-min.css" />


<link rel="stylesheet" href="http://www.zapquebec.org/wp-content/themes/zap_quebec/style.css" type="text/css" media="screen" />
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/style.css" type="text/css" media="screen" />
<!--[if IE 6]>
<link type="text/css" rel="stylesheet" href="http://www.zapquebec.org/wp-content/themes/zap_quebec/css/ie6.css" />
<![endif]-->

<!--[if IE 7]>
<link type="text/css" rel="stylesheet" href="http://www.zapquebec.org/wp-content/themes/zap_quebec/css/ie7.css" />
<![endif]-->

<script type="text/javascript" src="http://www.zapquebec.org/wp-content/themes/zap_quebec/js/jquery-1.3.min.js"></script>

</head>

<body>
<body class="yui-skin-sam">
	<div id="conteneur">
		<div id="content">
            <?php echo $this->layout()->content ?>
		</div>
	</div>
</body>
</html>




